// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            7
// Async Callback (empty):               1
// Total number of exported functions:  10

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    greenfund_contract
    (
        init => init
        upgrade => upgrade
        fund => fund
        claim => claim
        refund => refund
        getTarget => get_target
        getDeadline => get_deadline
        getTotalFunds => get_total_funds
        getDonation => get_donation
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
